# FontAwesome 5: https://fontawesome.com/icons?d=gallery&p=2&m=free
backlight_empty = "\U0001f315"
backlight_full = "\U0001f311"
backlight_1 = "\U0001f314"
backlight_2 = "\U0001f314"
backlight_3 = "\U0001f314"
backlight_4 = "\U0001f314"
backlight_5 = "\U0001f313"
backlight_6 = "\U0001f313"
backlight_7 = "\U0001f313"
backlight_8 = "\U0001f313"
backlight_9 = "\U0001f313"
backlight_10 = "\U0001f312"
backlight_11 = "\U0001f312"
backlight_12 = "\U0001f312"
backlight_13 = "\U0001f312"
bat_charging = "\uf1e6"
bat_discharging = "\uf242"
bat_not_available = "\uf244"
bat_empty = "\uf244" # TODO remove on next release
bat_10 = "\uf244"
bat_20 = "\uf243"
bat_30 = "\uf243"
bat_40 = "\uf243"
bat_50 = "\uf242"
bat_60 = "\uf242"
bat_70 = "\uf241"
bat_80 = "\uf241"
bat_90 = "\uf241"
bat_full = "\uf240"
bat_half = "\uf242" # TODO remove on next release
bat_quarter = "\uf243" # TODO remove on next release
bat_three_quarters = "\uf241" # TODO remove on next release
bell = "\uf0f3"
bell-slash = "\uf1f6"
bluetooth = "\uf294"
calendar = "\uf073"
cogs = "\uf085"
cpu = "\uf3fd"
cpu_boost_on = "\uf205"
cpu_boost_off = "\uf204"
disk_drive = "\uf0a0"
docker = "\uf21a"
github = "\uf09b"
gpu = "\uf26c"
headphones = "\uf025"
joystick = "\uf11b"
keyboard = "\uf11c"
mail = "\uf0e0"
memory_mem = "\uf2db"
memory_swap = "\uf0a0"
mouse = "\uf245"
music = "\uf001"
music_next = "\uf061"
music_pause = "\uf04c"
music_play = "\uf04b"
music_prev = "\uf060"
net_bridge = "\uf0e8"
net_down = "\uf019"
net_loopback = "LO"
net_modem = "\uf095"
net_up = "\uf093"
net_vpn = "\uf023"
net_wired = "\uf6ff"
net_wireless = "\uf1eb"
notification = "\uf0f3"
phone = "\uf3cd"
phone_disconnected = "\U0001f4f5"
ping = "\uf362"
pomodoro = "\U0001f345"
pomodoro_break = "\uf0f4" # fa-coffee
pomodoro_paused = "\uf04c" # fa-pause
pomodoro_started = "\uf04b" # fa-play
pomodoro_stopped = "\uf04d" # fa-stop
resolution = "\uf096" # fa-square-o
tasks = "\uf0ae"
thermometer = "\uf2c8"
time = "\uf017"
toggle_off = "\uf204"
toggle_on = "\uf205"
unknown = "\uf128"
update = "\uf062"
uptime = "\uf2f2"
volume_empty = "\uf026"
volume_full = "\uf028"
volume_half = "\uf027"
volume_muted = "\uf6a9"
microphone_full = "\uf3c9"
microphone_half = "\uf3c9"
microphone_empty = "\uf3c9"
microphone_muted = "\uf539"
weather_clouds = "\uf0c2"
weather_default = "\uf0c2" # Cloud symbol as default
weather_rain = "\uf043"
weather_snow = "\uf2dc"
weather_sun = "\uf185"
weather_thunder = "\uf0e7"
xrandr = "\uf26c"
