idle_bg = "#444444"
idle_fg = "#f5f5f5"
info_bg = "#626262"
info_fg = "#ffd680"
good_bg = "#afff00"
good_fg = "#000000"
warning_bg = "#ffaf00"
warning_fg = "#000000"
critical_bg = "#d70000"
critical_fg = "#000000"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
