idle_bg = "#282a36"
idle_fg = "#f8f8f2"
info_bg = "#8be9fd"
info_fg = "#282a36"
good_bg = "#50fa7b"
good_fg = "#282a36"
warning_bg = "#f1fa8c"
warning_fg = "#282a36"
critical_bg = "#ff5555"
critical_fg = "#282a36"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
