idle_bg = "#fb5aaa"
idle_fg = "#000000"
info_bg = "#ffd680"
info_fg = "#000000"
good_bg = "#afff00"
good_fg = "#000000"
warning_bg = "#f1b04c"
warning_fg = "#000000"
critical_bg = "#de3161"
critical_fg = "#000000"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
