idle_bg = "#fbf1c7"
idle_fg = "#3c3836"
info_bg = "#458588"
info_fg = "#fbf1c7"
good_bg = "#98971a"
good_fg = "#fbf1c7"
warning_bg = "#d79921"
warning_fg = "#fbf1c7"
critical_bg = "#cc241d"
critical_fg = "#fbf1c7"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto" 
