idle_bg = "#282828"
idle_fg = "#ebdbb2"
info_bg = "#458588"
info_fg = "#ebdbb2"
good_bg = "#98971a"
good_fg = "#ebdbb2"
warning_bg = "#d79921"
warning_fg = "#ebdbb2"
critical_bg = "#cc241d"
critical_fg = "#ebdbb2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
