idle_bg = "#222D32"
idle_fg = "#CFD8DC"
info_bg = "#449CDB"
info_fg = "#1D1F21"
good_bg = "#99b938"
good_fg = "#1D1F21"
warning_bg = "#FE7E29"
warning_fg = "#1D1F21"
critical_bg = "#ff5252"
critical_fg = "#1D1F21"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
