idle_bg = "#000000"
idle_fg = "#93a1a1"
info_bg = "#000000"
info_fg = "#93a1a1"
good_bg = "#000000"
good_fg = "#859900"
warning_bg  = "#000000"
warning_fg  = "#b58900"
critical_bg = "#000000"
critical_fg = "#dc322f"
separator = "|"
separator_bg = "#000000"
separator_fg = "#a9a9a9"
