idle_bg = "#424242"
idle_fg = "#ffffff"
info_bg = "#2196f3"
info_fg = "#ffffff"
good_bg = "#8bc34a"
good_fg = "#000000"
warning_bg = "#ffc107"
warning_fg = "#000000"
critical_bg = "#f44336"
critical_fg = "#ffffff"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"
