name: Man page release upload
on:
  release:
    types: [published]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  manpage:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel-20260920.0.596911@sha256:8745817f349ed24373341ddb92776209eeec3f0364ea48f7f645ac5800d30a50
    permissions:
      contents: write
    steps:
    - name: Get required packages and config git
      run: |
        pacman --noconfirm --noprogressbar --needed -Syu base-devel clang git libpipewire libpulse lm_sensors notmuch openssl pandoc github-cli
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@stable
    - name: Generate and upload manpage
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
        TAG_NAME: ${{ github.event.release.tag_name }}
      run: |
        cargo xtask generate-manpage
        gh release upload -R "$GH_REPO" --clobber "$TAG_NAME" ./man/i3status-rs.1
